from __future__ import annotations

import re
from dataclasses import dataclass, field
from typing import Iterable

from pydantic import BaseModel, Field

from memory_transferor.memory_models import PersistentMemoryItem
from memory_transferor.memory_export.display_taxonomy import base_display_taxonomy


class DisplayGroupHint(BaseModel):
    """Optional higher-level display taxonomy supplied by policy, LLM, or user edits."""

    group_id: str
    item_type: str
    label: str
    description: str = ""
    memory_ids: list[str] = Field(default_factory=list)
    match_terms: list[str] = Field(default_factory=list)


class KeywordDisplayItem(BaseModel):
    """Checkbox-oriented display item for high-level profile/preference keywords."""

    display_id: str
    label: str
    selected: bool = True
    description: str = ""
    tooltip: str = ""
    details: list[str] = Field(default_factory=list)
    source_memory_ids: list[str] = Field(default_factory=list)
    evidence_episode_ids: list[str] = Field(default_factory=list)
    evidence_turn_ids: list[str] = Field(default_factory=list)
    confidence: str = "medium"


class CardDisplayItem(BaseModel):
    """Phrase plus short description display item for non-checkbox memory types."""

    display_id: str
    type: str
    title: str
    summary: str = ""
    details: list[str] = Field(default_factory=list)
    source_memory_ids: list[str] = Field(default_factory=list)
    evidence_episode_ids: list[str] = Field(default_factory=list)
    evidence_turn_ids: list[str] = Field(default_factory=list)
    confidence: str = "medium"


class MemoryDisplayPayload(BaseModel):
    """Frontend-facing projection derived from persistent memory."""

    schema_version: str = "display.v1"
    language: str = "zh"
    profile_keywords: list[KeywordDisplayItem] = Field(default_factory=list)
    preference_keywords: list[KeywordDisplayItem] = Field(default_factory=list)
    project_cards: list[CardDisplayItem] = Field(default_factory=list)
    workflow_cards: list[CardDisplayItem] = Field(default_factory=list)
    daily_note_cards: list[CardDisplayItem] = Field(default_factory=list)
    skill_cards: list[CardDisplayItem] = Field(default_factory=list)


@dataclass
class _KeywordGroup:
    group_id: str
    item_type: str
    items: list[PersistentMemoryItem] = field(default_factory=list)
    tokens: set[str] = field(default_factory=set)
    hint: DisplayGroupHint | None = None


class MemoryDisplayBuilder:
    """Build a stable frontend display payload from persistent memory items.

    This layer should not hard-code domain-specific profile/preference families.
    The preferred path is to pass higher-level display taxonomy through
    `DisplayGroupHint`, which can be generated by policy, LLM summarization,
    clustering, or user-edited frontend state. Without hints, the builder only
    applies a generic token-similarity fallback so the UI still has a usable
    shape during tests.
    """

    def __init__(
        self,
        language: str = "auto",
        keyword_group_hints: Iterable[DisplayGroupHint] | None = None,
        use_base_taxonomy: bool = True,
        similarity_threshold: float = 0.18,
    ) -> None:
        self.language = language
        hints = self._base_taxonomy_hints() if use_base_taxonomy else []
        hints.extend(keyword_group_hints or [])
        self.keyword_group_hints = hints
        self.similarity_threshold = similarity_threshold

    def build(self, items: Iterable[PersistentMemoryItem]) -> MemoryDisplayPayload:
        rows = list(items)
        language = self._resolve_language(rows)
        profile_items = [item for item in rows if item.type == "profile"]
        preference_items = [item for item in rows if item.type == "preference"]

        return MemoryDisplayPayload(
            language=language,
            profile_keywords=self._build_keyword_items(profile_items, "profile", language),
            preference_keywords=self._build_keyword_items(preference_items, "preference", language),
            project_cards=self._build_cards([item for item in rows if item.type == "topic"], "project", language),
            workflow_cards=self._build_cards([item for item in rows if item.type == "workflow"], "workflow", language),
            daily_note_cards=self._build_cards(
                [item for item in rows if item.type == "daily_note"], "daily_note", language
            ),
            skill_cards=self._build_cards([item for item in rows if item.type == "skill"], "skill", language),
        )

    def _resolve_language(self, items: list[PersistentMemoryItem]) -> str:
        requested = self.language.lower()
        if requested in {"zh", "zh-cn", "chinese"}:
            return "zh"
        if requested in {"en", "en-us", "english"}:
            return "en"
        joined = "\n".join(f"{item.key}\n{item.description}" for item in items)
        lowered = joined.lower()
        if "中文" in joined or "chinese" in lowered or _cjk_count(joined) >= 8:
            return "zh"
        return "en"

    def _base_taxonomy_hints(self) -> list[DisplayGroupHint]:
        hints: list[DisplayGroupHint] = []
        for category, item_type in [("profile", "profile"), ("preferences", "preference")]:
            for group in base_display_taxonomy(category):
                title = group.get("title", {})
                label = title.get("zh") if isinstance(title, dict) else str(title or "")
                hints.append(
                    DisplayGroupHint(
                        group_id=str(group.get("group_id") or ""),
                        item_type=item_type,
                        label=str(label or group.get("group_id") or ""),
                        description="",
                        match_terms=[
                            str(term)
                            for term in [
                                *(group.get("source_fields", []) or []),
                                *(group.get("match_terms", []) or []),
                            ]
                            if str(term).strip()
                        ],
                    )
                )
        return hints

    def _build_keyword_items(
        self,
        items: list[PersistentMemoryItem],
        item_type: str,
        language: str,
    ) -> list[KeywordDisplayItem]:
        display_items: list[KeywordDisplayItem] = []
        for group in self._build_keyword_groups(items, item_type):
            primary = max(group.items, key=lambda item: _priority_score(item.export_priority))
            details = _unique_preserve_order(self._detail_line(item) for item in group.items)
            display_items.append(
                KeywordDisplayItem(
                    display_id=f"{item_type}:{group.group_id}",
                    label=self._keyword_label(group, language, primary),
                    description=self._keyword_description(group, language),
                    tooltip=self._tooltip(details, language),
                    details=details,
                    source_memory_ids=_unique_preserve_order(item.memory_id for item in group.items),
                    evidence_episode_ids=_unique_preserve_order(
                        episode_id for item in group.items for episode_id in item.evidence_episode_ids
                    ),
                    evidence_turn_ids=_unique_preserve_order(
                        turn_id for item in group.items for turn_id in item.evidence_turn_ids
                    ),
                    confidence=_highest_confidence(item.confidence for item in group.items),
                )
            )
        return sorted(display_items, key=lambda item: (item.label, item.display_id))

    def _build_keyword_groups(
        self,
        items: list[PersistentMemoryItem],
        item_type: str,
    ) -> list[_KeywordGroup]:
        groups: list[_KeywordGroup] = []
        assigned_memory_ids: set[str] = set()
        hints = [hint for hint in self.keyword_group_hints if hint.item_type == item_type]

        for hint in hints:
            group_items = [
                item for item in items if item.memory_id not in assigned_memory_ids and self._matches_hint(item, hint)
            ]
            if not group_items:
                continue
            group = _KeywordGroup(
                group_id=self._slug(hint.group_id),
                item_type=item_type,
                items=group_items,
                tokens=_tokens_for_items(group_items),
                hint=hint,
            )
            groups.append(group)
            assigned_memory_ids.update(item.memory_id for item in group_items)

        remaining_items = [item for item in items if item.memory_id not in assigned_memory_ids]
        for item in sorted(remaining_items, key=lambda row: (_priority_rank(row.export_priority), row.key)):
            item_tokens = _tokens_for_item(item)
            best_group = self._best_dynamic_group(groups, item_tokens)
            if best_group is None:
                groups.append(
                    _KeywordGroup(
                        group_id=self._slug(f"auto-{item.key or item.memory_id}"),
                        item_type=item_type,
                        items=[item],
                        tokens=set(item_tokens),
                    )
                )
                continue
            best_group.items.append(item)
            best_group.tokens.update(item_tokens)

        return groups

    def _matches_hint(self, item: PersistentMemoryItem, hint: DisplayGroupHint) -> bool:
        if item.memory_id in set(hint.memory_ids):
            return True
        text = f"{item.key}\n{item.description}".lower()
        return any(term.lower() in text for term in hint.match_terms)

    def _best_dynamic_group(self, groups: list[_KeywordGroup], item_tokens: set[str]) -> _KeywordGroup | None:
        best_group: _KeywordGroup | None = None
        best_score = 0.0
        for group in groups:
            if group.hint is not None:
                continue
            score = _token_similarity(item_tokens, group.tokens)
            if score > best_score:
                best_group = group
                best_score = score
        if best_score < self.similarity_threshold:
            return None
        return best_group

    def _build_cards(
        self,
        items: list[PersistentMemoryItem],
        display_type: str,
        language: str,
    ) -> list[CardDisplayItem]:
        cards: list[CardDisplayItem] = []
        for item in sorted(items, key=lambda row: (_priority_rank(row.export_priority), row.key)):
            details = [step for step in item.steps if step]
            if not details and item.description:
                details = [item.description]
            cards.append(
                CardDisplayItem(
                    display_id=f"{display_type}:{item.memory_id}",
                    type=display_type,
                    title=self._card_title(item),
                    summary=self._short_summary(item.description, language),
                    details=details,
                    source_memory_ids=[item.memory_id],
                    evidence_episode_ids=item.evidence_episode_ids,
                    evidence_turn_ids=item.evidence_turn_ids,
                    confidence=item.confidence,
                )
            )
        return cards

    def _keyword_label(
        self,
        group: _KeywordGroup,
        language: str,
        primary: PersistentMemoryItem,
    ) -> str:
        if group.hint is not None and group.hint.label:
            return group.hint.label
        ranked_terms = _rank_label_terms(group.items, language)
        if ranked_terms:
            return _format_label_terms(ranked_terms[:2], language)
        return self._title_from_key(primary.key)

    def _keyword_description(self, group: _KeywordGroup, language: str) -> str:
        if group.hint is not None and group.hint.description:
            return group.hint.description
        count = len(group.items)
        if language == "zh":
            type_name = "用户画像" if group.item_type == "profile" else "偏好规则"
            return f"由 {count} 条{type_name}归纳，具体细节见详情。"
        type_name = "profile memories" if group.item_type == "profile" else "preference rules"
        return f"Derived from {count} {type_name}; see details for fine-grained rules."

    def _card_title(self, item: PersistentMemoryItem) -> str:
        return self._title_from_key(item.key)

    def _title_from_key(self, key: str) -> str:
        cleaned = re.sub(r"[_\-]+", " ", key).strip()
        if not cleaned:
            return "Untitled"
        return cleaned[:1].upper() + cleaned[1:]

    def _short_summary(self, text: str, language: str) -> str:
        cleaned = " ".join(str(text or "").split())
        if len(cleaned) <= 96:
            return cleaned
        end = "。" if language == "zh" else "."
        return cleaned[:96].rstrip(" ,，.;；。") + end

    def _detail_line(self, item: PersistentMemoryItem) -> str:
        if item.description:
            return item.description
        return self._title_from_key(item.key)

    def _tooltip(self, details: list[str], language: str) -> str:
        if not details:
            return ""
        prefix = "包含细化规则：" if language == "zh" else "Includes detailed rules: "
        return prefix + "；".join(details[:4])

    def _slug(self, value: str) -> str:
        slug = re.sub(r"[^a-zA-Z0-9_\-\u4e00-\u9fff]+", "-", value.strip()).strip("-").lower()
        return slug or "group"


def _tokens_for_items(items: Iterable[PersistentMemoryItem]) -> set[str]:
    tokens: set[str] = set()
    for item in items:
        tokens.update(_tokens_for_item(item))
    return tokens


def _tokens_for_item(item: PersistentMemoryItem) -> set[str]:
    text = f"{item.key}\n{item.description}\n" + "\n".join(item.steps)
    return _extract_tokens(text)


def _extract_tokens(text: str) -> set[str]:
    tokens: set[str] = set()
    normalized = re.sub(r"[_\-]+", " ", text.lower())
    for token in re.findall(r"[a-z0-9]+", normalized):
        if len(token) >= 3 and token not in _ENGLISH_STOPWORDS:
            tokens.add(token)
    for run in re.findall(r"[\u4e00-\u9fff]{2,}", normalized):
        cleaned = _strip_cjk_prefix(run)
        if 2 <= len(cleaned) <= 8 and cleaned not in _CJK_STOPWORDS:
            tokens.add(cleaned)
        for size in (2, 3):
            for index in range(0, max(len(cleaned) - size + 1, 0)):
                piece = cleaned[index : index + size]
                if piece not in _CJK_STOPWORDS:
                    tokens.add(piece)
    return tokens


def _rank_label_terms(items: list[PersistentMemoryItem], language: str) -> list[str]:
    scores: dict[str, float] = {}
    first_seen: dict[str, int] = {}
    for item_index, item in enumerate(items):
        item_text = f"{item.key}\n{item.description}"
        for term in _extract_label_candidates(item_text, language):
            scores[term] = scores.get(term, 0.0) + 1.0 + _priority_score(item.export_priority) * 0.1
            first_seen.setdefault(term, item_index)
    ranked = sorted(
        scores,
        key=lambda term: (-scores[term], _language_term_rank(term, language), first_seen[term], -len(term)),
    )
    return ranked


def _extract_label_candidates(text: str, language: str) -> list[str]:
    candidates: list[str] = []
    normalized = re.sub(r"[_\-]+", " ", text.lower())
    if language == "zh":
        english_words = [
            token
            for token in re.findall(r"[a-z0-9]+", normalized)
            if len(token) >= 3 and token not in _ENGLISH_STOPWORDS
        ]
        candidates.extend(" ".join(english_words[index : index + 2]) for index in range(max(len(english_words) - 1, 0)))
        for chunk in re.split(r"[\s,，.。;；:：/、()\[\]{}]+", normalized):
            if not chunk:
                continue
            if _has_cjk(chunk):
                cleaned = _strip_cjk_prefix(chunk)
                if 2 <= len(cleaned) <= 10 and cleaned not in _CJK_STOPWORDS:
                    candidates.append(cleaned)
                candidates.extend(
                    piece
                    for piece in _extract_tokens(cleaned)
                    if _has_cjk(piece) and piece not in _CJK_STOPWORDS
                )
            else:
                candidates.extend(
                    token
                    for token in re.findall(r"[a-z0-9]+", chunk)
                    if len(token) >= 3 and token not in _ENGLISH_STOPWORDS
                )
    else:
        words = [
            token
            for token in re.findall(r"[a-z0-9]+", normalized)
            if len(token) >= 3 and token not in _ENGLISH_STOPWORDS
        ]
        candidates.extend(words)
        candidates.extend(" ".join(words[index : index + 2]) for index in range(max(len(words) - 1, 0)))
    return _unique_preserve_order(candidates)


def _format_label_terms(terms: list[str], language: str) -> str:
    if not terms:
        return "关键词" if language == "zh" else "Keyword"
    if language == "zh":
        cjk_terms = [term for term in terms if _has_cjk(term)]
        if cjk_terms:
            if len(cjk_terms[0]) >= 3:
                return cjk_terms[0][:10]
            return "".join(cjk_terms[:2])[:10]
    return " / ".join(_title_case(term) for term in terms[:2])


def _language_term_rank(term: str, language: str) -> int:
    if language == "zh":
        return 0 if _has_cjk(term) else 1
    return 1 if _has_cjk(term) else 0


def _strip_cjk_prefix(text: str) -> str:
    prefixes = ("用户", "偏好", "需要", "希望", "要求", "避免", "使用", "输出", "保持", "通过", "有", "应")
    cleaned = text
    changed = True
    while changed:
        changed = False
        for prefix in prefixes:
            if cleaned.startswith(prefix) and len(cleaned) > len(prefix) + 1:
                cleaned = cleaned[len(prefix) :]
                changed = True
    return cleaned


def _token_similarity(left: set[str], right: set[str]) -> float:
    if not left or not right:
        return 0.0
    shared = len(left & right)
    return shared / min(len(left), len(right))


def _has_cjk(text: str) -> bool:
    return _cjk_count(text) > 0


def _cjk_count(text: str) -> int:
    return sum(1 for char in text if "\u4e00" <= char <= "\u9fff")


def _unique_preserve_order(values: Iterable[str]) -> list[str]:
    seen: set[str] = set()
    result: list[str] = []
    for value in values:
        if not value or value in seen:
            continue
        seen.add(value)
        result.append(value)
    return result


def _title_case(value: str) -> str:
    return " ".join(part[:1].upper() + part[1:] for part in value.split())


def _priority_score(priority: str) -> int:
    return {"high": 3, "medium": 2, "low": 1}.get(priority, 0)


def _priority_rank(priority: str) -> int:
    return {"high": 0, "medium": 1, "low": 2}.get(priority, 3)


def _highest_confidence(values: Iterable[str]) -> str:
    ranked = sorted(values, key=lambda value: {"high": 0, "medium": 1, "low": 2}.get(value, 3))
    return ranked[0] if ranked else "medium"


_ENGLISH_STOPWORDS = {
    "and",
    "are",
    "can",
    "for",
    "from",
    "has",
    "into",
    "not",
    "the",
    "this",
    "that",
    "their",
    "user",
    "uses",
    "with",
}

_CJK_STOPWORDS = {
    "一个",
    "一些",
    "可以",
    "用户",
    "偏好",
    "需要",
    "希望",
    "要求",
    "避免",
    "使用",
    "输出",
    "保持",
    "通过",
    "进行",
    "相关",
    "内容",
    "方式",
}
